# Generated by Django 4.1.2 on 2022-10-30 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socmedia',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='socmedia/%Y/%m/%d/'),
        ),
    ]
