# Generated by Django 4.1.2 on 2022-10-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_socmedia_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socmedia',
            name='link',
            field=models.URLField(),
        ),
    ]
